namespace IM800Asm;

internal class Assembler
{
	/// <summary>
	/// Statements generated by the parser
	/// </summary>
	private List<Statement> _statements;

	/// <summary>
	/// Position in the statements list
	/// </summary>
	private int _position;

	/// <summary>
	/// Position in the assembled file
	/// </summary>
	private int _locationCounter;

	/// <summary>
	/// Current scope for local labels (name of last non-local label)
	/// </summary>
	private string _currentScope;

	/// <summary>
	/// Dictionary of symbol names to values
	/// </summary>
	private Dictionary<string, long> _symbolTable;

	public Assembler(List<Statement> statements)
	{
		_statements = statements;
		_position = 0;
		_locationCounter = 0;
		_currentScope = string.Empty;
		_symbolTable = [];
	}

	public Result<List<byte>> Assemble()
	{
		Result<List<byte>> result = new([]);

		Result passOneResult = PassOne();
		result.Combine(passOneResult);

		if (result.IsSuccess)
		{
			Result<List<byte>> passTwoResult = PassTwo();
			result.Combine(passTwoResult);
			result.ResultObject = passTwoResult.ResultObject;
		}

		return result;
	}

	// Walks statements, collecting symbols and measuring sizes
	// Evaluates .ORG, .DEFS, .EQU expressions
	private Result PassOne()
	{
		Result result = new();

		return result;
	}

	// Walks statements again, evaluating expressions and emitting bytes
	private Result<List<byte>> PassTwo()
	{
		Result<List<byte>> result = new([]);

		return result;
	}
}