using System.Diagnostics;

namespace IM800Asm;

internal partial class Assembler
{
	/// <summary>
	/// Statements generated by the parser
	/// </summary>
	private List<Statement> _statements;

	/// <summary>
	/// Position in the assembled file
	/// </summary>
	private long _locationCounter;

	/// <summary>
	/// Current scope for local labels (name of last non-local label)
	/// </summary>
	private string _currentScope;

	/// <summary>
	/// Dictionary of symbol names to values
	/// </summary>
	private Dictionary<string, long> _symbolTable;

	public IReadOnlyDictionary<string, long> SymbolTable => _symbolTable;

	/// <summary>
	/// Used by .EQU to redefine the last defined symbol
	/// </summary>
	private string _lastDefinedSymbol;

	private ExpressionEvaluator _evaluator;

	private List<byte> _data;

	public Assembler(List<Statement> statements)
	{
		_statements = statements;
		_locationCounter = 0;
		_currentScope = string.Empty;
		_symbolTable = [];
		_lastDefinedSymbol = string.Empty;
		_evaluator = new(GetSymbol);
		_data = [];
	}

	public Result<List<byte>> Assemble()
	{
		Result<List<byte>> result = new(_data);

		Result passOneResult = PassOne();
		result.Combine(passOneResult);

		if (result.IsSuccess)
		{
			Result passTwoResult = PassTwo();
			result.Combine(passTwoResult);
		}

		return result;
	}

	// Walks statements, collecting symbols and measuring sizes
	// Evaluates .ORG, .DEFS, .EQU expressions
	private Result PassOne()
	{
		Result result = new();

		foreach (Statement st in _statements)
		{
			if (st is LabelStatement ls)
			{
				if (TryDefineSymbol(ls.Text, _locationCounter))
				{
					_lastDefinedSymbol = ls.Text;

					if (!ls.Text.StartsWith('.'))
					{
						_currentScope = ls.Text;
					}
				}
				else
				{
					result.AddError("Assembler", $"{ls.Line}:{ls.Text}:\tcannot redefine symbol \"{ls.Text}\"");
				}
			}
			else if (st is DirectiveStatement ds)
			{
				Result<long> directiveResult = EmitDirectivePassOne(ds);
				result.Combine(directiveResult);
				_locationCounter += directiveResult.ResultObject;
				_lastDefinedSymbol = string.Empty;
			}
			else if (st is InstructionStatement inst)
			{
				if (InstructionTable.TryResolveInstruction(inst, out InstructionTable.Entry? entry))
				{
					Debug.Assert(entry is not null);

					FixupInstruction(inst, entry);

					Result<long> instructionResult = entry.InstructionFormat switch
					{
						Constants.InstructionFormat.R => MeasureFormatR(inst, entry),
						Constants.InstructionFormat.RM => MeasureFormatRM(inst, entry),
						Constants.InstructionFormat.UR => MeasureFormatUR(inst, entry),
						Constants.InstructionFormat.UM => MeasureFormatUM(inst, entry),
						Constants.InstructionFormat.B => MeasureFormatB(inst, entry),
						Constants.InstructionFormat.M => MeasureFormatM(inst, entry),
						Constants.InstructionFormat.SB => MeasureFormatSB(inst, entry),
						Constants.InstructionFormat.BLK => MeasureFormatBLK(inst, entry),
						_ => throw new Exception($"Unexpected instruction format {entry.InstructionFormat} in pass 1"),
					};

					result.Combine(instructionResult);
					_locationCounter += instructionResult.ResultObject;
				}
				else
				{
					result.AddError(
						"Assembler",
						$"{inst.Line}:{inst.Column}:\tinvalid operands for instruction {inst.Instruction}"
					);
				}

				_lastDefinedSymbol = string.Empty;
			}
		}

		return result;
	}

	// Walks statements again, evaluating expressions and emitting bytes into _data
	private Result PassTwo()
	{
		Result result = new();

		foreach (Statement st in _statements)
		{
			if (st is LabelStatement ls)
			{
				if (!ls.Text.StartsWith('.'))
				{
					_currentScope = ls.Text;
				}
			}
			else if (st is DirectiveStatement ds)
			{
				Result<long> directiveResult = EmitDirectivePassTwo(ds);
				result.Combine(directiveResult);
				_locationCounter += directiveResult.ResultObject;
				_lastDefinedSymbol = string.Empty;
			}
			else if (st is InstructionStatement inst)
			{
				if (InstructionTable.TryResolveInstruction(inst, out InstructionTable.Entry? entry))
				{
					Debug.Assert(entry is not null);
					Result<long> instructionResult = entry.InstructionFormat switch
					{
						Constants.InstructionFormat.R => EmitFormatR(inst, entry),
						Constants.InstructionFormat.RM => EmitFormatRM(inst, entry),
						Constants.InstructionFormat.UR => EmitFormatUR(inst, entry),
						Constants.InstructionFormat.UM => EmitFormatUM(inst, entry),
						Constants.InstructionFormat.B => EmitFormatB(inst, entry),
						Constants.InstructionFormat.M => EmitFormatM(inst, entry),
						Constants.InstructionFormat.SB => EmitFormatSB(inst, entry),
						Constants.InstructionFormat.BLK => EmitFormatBLK(inst, entry),
						_ => throw new Exception($"Unexpected instruction format {entry.InstructionFormat} in pass 1"),
					};

					result.Combine(instructionResult);
					_locationCounter += instructionResult.ResultObject;
				}
				else
				{
					result.AddError(
						"Assembler",
						$"{inst.Line}:{inst.Column}:\tinvalid operands for instruction {inst.Instruction}"
					);
				}

				_lastDefinedSymbol = string.Empty;
			}
		}

		return result;
	}

	/// <summary>
	/// Defines a symbol if it's not already defined
	/// </summary>
	/// <param name="symbol">Symbol name. Will be expanded to fully qualified name.</param>
	/// <param name="value"></param>
	/// <returns>true if successful, false if symbol is already defined</returns>
	private bool TryDefineSymbol(string symbol, long value)
	{
		string qualifiedName = GetQualifiedName(symbol);

		if (_symbolTable.ContainsKey(qualifiedName))
		{
			return false;
		}

		_symbolTable[qualifiedName] = value;
		return true;
	}

	/// <summary>
	/// Defines or redefines a symbol. Used by .EQU.
	/// </summary>
	/// <param name="symbol">Symbol name. Will be expanded to fully qualified name.</param>
	/// <param name="value"></param>
	private void RedefineSymbol(string symbol, long value)
	{
		string qualifiedName = GetQualifiedName(symbol);
		_symbolTable[qualifiedName] = value;
	}

	/// <summary>
	/// Gets a symbol's value
	/// </summary>
	/// <param name="symbol">Symbol name. Will be expanded to fully qualified name.</param>
	/// <returns>value, or null if not found</returns>
	private long? GetSymbol(string symbol)
	{
		string qualifiedName = GetQualifiedName(symbol);

		if (!_symbolTable.ContainsKey(qualifiedName))
		{
			return null;
		}

		return _symbolTable[qualifiedName];
	}

	/// <summary>
	/// Gets a symbol's qualified name. Either the symbol itself, or the current scope + local label name
	/// </summary>
	/// <param name="symbol"></param>
	/// <returns></returns>
	private string GetQualifiedName(string symbol)
	{
		if (symbol.StartsWith('.'))
		{
			return _currentScope + symbol;
		}

		return symbol;
	}

	private void EmitValue(long value, Constants.Size size)
	{
		switch (size)
		{
			case Constants.Size.Byte:
			{
				_data.Add((byte)value);
				break;
			}
			case Constants.Size.Word:
			{
				_data.Add((byte)value);
				_data.Add((byte)(value >> 8));
				break;
			}
			case Constants.Size.Dword:
			{
				_data.Add((byte)value);
				_data.Add((byte)(value >> 8));
				_data.Add((byte)(value >> 16));
				_data.Add((byte)(value >> 24));
				break;
			}
			case Constants.Size.Qword:
			{
				_data.Add((byte)value);
				_data.Add((byte)(value >> 8));
				_data.Add((byte)(value >> 16));
				_data.Add((byte)(value >> 24));
				_data.Add((byte)(value >> 32));
				_data.Add((byte)(value >> 40));
				_data.Add((byte)(value >> 48));
				_data.Add((byte)(value >> 56));
				break;
			}
		}
	}
}